name: ci

on:
  push:
    branches:
      - master
      - develop

  schedule:
    - cron: "0 9 * * *"

env:
  NODE_VERSION: 10.x

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: "Get yarn cache directory path"
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: "Restore yarn cache"
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install

  build:
    strategy:
      matrix:
        type: ["web:dev", "desktop:win32", "desktop:darwin"]
    runs-on: ${{
      (matrix.type == 'desktop:win32' && 'windows-latest') || 'macos-latest'
      }}
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: "Get yarn cache directory path"
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: "Restore yarn cache"
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install

      - run: yarn build:share
      - run: yarn build:${{ matrix.type }}
